services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
